# escape=`
FROM @BASEIMAGE@
SHELL ["cmd", "/S", "/C"]
ADD setup-x86_64.exe /
RUN setup-x86_64.exe -s http://ftp.iij.ad.jp/pub/cygwin -R c:\cyg64 -l c:\cache64 -B -v -q -N -d -g -P  libiconv-devel,libisl10,cloog-isl,cmake,git,gcc,make,gcc-g++,automake,autoconf,libtool,libgmp-devel,libonig-devel,flex,gettext-devel,pkg-config,libunistring-devel,libffi-devel,libgc-devel,texinfo,zlib-devel && rmdir c:\cache64 /s /q
ADD noaslr-cygwin1.dll /
RUN move \noaslr-cygwin1.dll c:\cyg64\bin\cygwin1.dll
LABEL org.opencontainers.image.source=https://github.com/okuoku/yunibuild
